const fs = require("fs")
const h = fs.readFileSync("C:/Users/xomoe/ecomm/zmobile/pdp-live.html", "utf8")
const i = h.indexOf("BAILOUT")
console.log("bailout ctx:", h.slice(Math.max(0, i - 150), i + 250))
const body = h.slice(h.indexOf("<body"), h.indexOf("</body>"))
console.log("lcp-hero:", (body.match(/data-lcp-hero/g) || []).length)
console.log("dgst count:", (body.match(/data-dgst/g) || []).length)
console.log("skeleton:", body.includes("animate-skeleton-pulse"))
console.log("vivo img in first 80k body:", body.slice(0, 80000).includes("vivo-v70"))
const scripts = [...h.matchAll(/<script[^>]*src="([^"]+)"/g)].map((m) => m[1])
console.log("scripts:", scripts.length)
console.log("third party:", scripts.filter((s) => !s.startsWith("/_next")))
