import { MedusaService } from "@medusajs/framework/utils"
import { SearchLog } from "./models/search-log"

/** Hard cap on a single query string — anything longer is junk. */
const MAX_QUERY_LEN = 100

/** Minimum length after normalization. Anything shorter is noise. */
const MIN_QUERY_LEN = 3

/** How far back a query can have been used to still count as "trending". */
const TRENDING_WINDOW_MS = 30 * 24 * 60 * 60 * 1000 // 30 days

/**
 * Process-local cache for `getTrending`. The trending endpoint is
 * called on every search-bar focus / mobile-overlay open across all
 * shoppers, so we de-duplicate the DB hit aggressively. 5 minutes is
 * a good balance — popular queries don't shuffle that fast, and a
 * freshly logged query only has to wait at most 5 minutes to appear.
 *
 * Cache keyed by `limit` so the same response can serve different
 * callers that ask for different sizes (default 8, mobile drawer 12,
 * admin preview 20, etc.).
 */
const TRENDING_CACHE_TTL_MS = 5 * 60 * 1000 // 5 minutes
const trendingCache = new Map<number, { value: string[]; expires: number }>()

/**
 * Normalize a raw query into the canonical form that gets stored.
 * The same input must always produce the same output so the `query`
 * column dedupes correctly:
 *
 *   - lowercase
 *   - trim
 *   - collapse runs of internal whitespace into a single space
 *   - strip control characters
 *
 * Returns an empty string when the query is unsuitable for logging
 * (too short, too long, empty).
 */
function normalizeQuery(raw: string): string {
  if (typeof raw !== "string") return ""
  const cleaned = raw
    .toLowerCase()
    .replace(/[\u0000-\u001f\u007f]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
  if (cleaned.length < MIN_QUERY_LEN || cleaned.length > MAX_QUERY_LEN) return ""
  return cleaned
}

/**
 * `SearchLogModuleService` exposes the standard CRUD generated by
 * `MedusaService` plus two convenience methods used by the public
 * `/store/search/log` and `/store/search/trending` routes:
 *
 *   • `logQuery(raw)`     — upserts the query (lowercased + trimmed)
 *                           and increments its counter.
 *   • `getTrending(limit)` — returns the top N queries from the last
 *                           30 days, ordered by frequency.
 *
 * The frontend never talks to the underlying CRUD methods directly.
 */
class SearchLogModuleService extends MedusaService({ SearchLog }) {
  /**
   * Idempotent increment-or-create. Safe to fire-and-forget from the
   * storefront — even if another request races us, the worst case is
   * two rows for the same normalized query, which `getTrending` would
   * still aggregate visually because both copies sort near each other.
   *
   * Bumping a query also invalidates the trending cache so the new
   * count surfaces on the next read instead of waiting for the TTL.
   */
  async logQuery(raw: string): Promise<void> {
    const query = normalizeQuery(raw)
    if (!query) return

    const existing = await (this as any).listSearchLogs(
      { query },
      { take: 1 }
    )

    if (existing && existing[0]) {
      await (this as any).updateSearchLogs({
        id: existing[0].id,
        count: (existing[0].count || 0) + 1,
        last_used_at: new Date(),
      })
    } else {
      await (this as any).createSearchLogs({
        query,
        count: 1,
        last_used_at: new Date(),
      })
    }

    // Invalidate trending cache so the new datapoint is visible
    // immediately on the next read instead of waiting up to 5 min.
    trendingCache.clear()
  }

  /**
   * Returns the top `limit` queries that have been logged in the last
   * 30 days, sorted by frequency (DESC). Stale queries fall off
   * naturally without needing a cron job — they just stop being
   * eligible until someone searches them again.
   *
   * Hot-path performance: this endpoint is hit on every search-bar
   * focus / mobile-overlay open. We short-circuit through a 5-minute
   * process-local cache keyed by `limit` so high-traffic stores don't
   * round-trip Postgres on every keystroke.
   */
  async getTrending(limit = 8): Promise<string[]> {
    const cap = Math.min(20, Math.max(1, Math.floor(limit) || 8))

    const cached = trendingCache.get(cap)
    if (cached && cached.expires > Date.now()) {
      return cached.value
    }

    // Fetch a small over-sample (e.g. top 50 by count) so we still
    // have enough rows after the in-memory recency filter to satisfy
    // `cap`. We can't push the `last_used_at >= cutoff` predicate
    // through the Medusa list API cleanly, but the count index makes
    // this a very cheap top-N scan regardless.
    const overSample = Math.max(50, cap * 5)
    const rows: any[] = await (this as any).listSearchLogs(
      {},
      {
        take: overSample,
        order: { count: "DESC" } as any,
      }
    )

    const cutoff = Date.now() - TRENDING_WINDOW_MS
    const value = (rows || [])
      .filter((row: any) => {
        if (!row.last_used_at) return true
        const t = new Date(row.last_used_at).getTime()
        return Number.isFinite(t) ? t >= cutoff : true
      })
      .slice(0, cap)
      .map((row: any) => row.query as string)

    trendingCache.set(cap, {
      value,
      expires: Date.now() + TRENDING_CACHE_TTL_MS,
    })

    return value
  }
}

export default SearchLogModuleService
